name: htyper
version: 0.1.0.0
github: "Simon-Hostettler/htyper"
license: BSD3
author: "Simon Hostettler"
maintainer: "simon.hostettler@protonmail.com"
copyright: "2022 Simon Hostettler"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Simon-Hostettler/htyper#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - directory
  - cursor
  - split
  - random
  - random-shuffle
  - time
  - optparse-applicative
  - terminal-size
  - formatting
  - text
library:
  source-dirs: src

data-dir: textfiles
data-files:
  - 1000us.txt
  - quotes.txt
  - results.txt

executables:
  htyper:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - htyper

tests:
  htyper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - htyper
